spring:
  application:
    name: userService
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: default

  datasource:
    url: jdbc:h2:mem:userServiceTestDB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      format_sql: true

  h2:
    console:
      enabled: true


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs


server:
  port: 8083

logging:
  level:
    org.hibernate.sql: debug

